enableTelemetry: false
packageExtensions:
  '@apidevtools/json-schema-ref-parser@9.1.0':
    dependencies:
      url: ^0.11.0
  '@axelar-network/axelarjs-sdk@0.6.20':
    dependencies:
      '@cosmjs/encoding': ^0.28.13
      '@cosmjs/proto-signing': ^0.28.13
      '@cosmjs/tendermint-rpc': ^0.28.13
      '@ethersproject/abi': ^5.7.0
      cosmjs-types: ^0.5.2
  '@ethereumjs/common@2.6.5':
    dependencies:
      events: ^3.3.0
  '@findeth/abi@0.3.1':
    dependencies:
      util: ^0.12.5
  '@jsdevtools/ono@7.1.3':
    dependencies:
      util: ^0.12.5
  '@json-rpc-tools/types@1.7.6':
    dependencies:
      tslib: ^2.4.1
  '@json-rpc-tools/utils@1.7.6':
    dependencies:
      tslib: ^2.4.1
  '@keepkey/caip@8.4.4':
    dependencies:
      lodash: 4.17.21
  '@keepkey/chain-adapters@10.2.1':
    dependencies:
      '@ethersproject/contracts': ^5.7.0
      '@keepkey/logger': ^1.1.3
  '@keepkey/device-protocol@7.10.2':
    dependencies:
      '@types/google-protobuf': ^3.5.16
  '@keepkey/investor-idle@2.1.5':
    dependencies:
      '@keepkey/logger': ^1.1.3
      axios: ^0.26.1
  '@keepkey/investor-yearn@6.1.7':
    dependencies:
      '@ethersproject/abi': ^5.7.0
      '@ethersproject/address': ^5.7.0
      '@ethersproject/bignumber': ^5.7.0
      '@ethersproject/bytes': ^5.7.0
      '@ethersproject/contracts': ^5.7.0
      '@keepkey/logger': ^1.1.3
  '@keepkey/market-service@7.1.3':
    dependencies:
      '@ethersproject/abi': ^5.7.0
      '@ethersproject/address': ^5.7.0
      '@ethersproject/bignumber': ^5.7.0
      '@ethersproject/bytes': ^5.7.0
      '@ethersproject/contracts': ^5.7.0
      '@keepkey/logger': ^1.1.3
      lodash: 4.17.21
  '@keepkey/swapper@14.2.0':
    dependencies:
      '@ethersproject/constants': ^5.7.0
      ethers: ^5.7.2
      web3-utils: ^1.8.1
  '@keepkey/unchained-client@10.3.0':
    dependencies:
      '@ethersproject/abi': ^5.7.0
      '@ethersproject/address': ^5.7.0
      '@ethersproject/bignumber': ^5.7.0
      '@ethersproject/bytes': ^5.7.0
      '@ethersproject/contracts': ^5.7.0
      '@ethersproject/providers': ^5.7.0
  '@pioneer-platform/pioneer-client@8.1.29':
    dependencies:
      js-yaml: ^3.13.1
  '@sentry/electron@4.1.2':
    dependencies:
      electron: 16.0.7
  '@shapeshiftoss/hdwallet-core@1.40.0':
    dependencies:
      '@ethersproject/bytes': ^5.7.0
      '@types/google-protobuf': ^3.5.16
      '@types/node': ^18
  '@shapeshiftoss/hdwallet-keepkey@1.40.0':
    dependencies:
      assert: ^2.0.0
      bs58: ^4.0.1
      bs58check: ^2.1.2
      create-hash: ^1.2.0
      ethers: ^5.7.2
      long: ^4.0.0
  '@shapeshiftoss/proto-tx-builder@0.4.0':
    dependencies:
      protobufjs: ^7.1.2
  '@solana/web3.js@1.52.0':
    dependencies:
      react: 18.1.0
      react-native: 0.70.6
  '@tanstack/query-sync-storage-persister@4.18.0':
    dependencies:
      '@tanstack/query-core': ^4.18.0
  '@tanstack/react-query-persist-client@4.18.0':
    dependencies:
      '@tanstack/query-core': ^4.18.0
      react: ^18.2.0
  '@tanstack/react-query@4.18.0':
    dependencies:
      react: ^18.2.0
      react-dom: ^18.2.0
  '@types/react-datepicker@4.8.0':
    dependencies:
      react: ^18.2.0
      react-dom: ^18.2.0
  '@unstoppabledomains/resolution@8.3.3':
    dependencies:
      js-sha3: ^0.8.0
  '@visx/annotation@2.12.2':
    dependencies:
      react-dom: ^18.2.0
  '@visx/xychart@2.16.0':
    dependencies:
      react-dom: ^18.2.0
  '@walletconnect/browser-utils@1.8.0':
    dependencies:
      tslib: ^2.4.1
  '@walletconnect/client@1.8.0':
    dependencies:
      tslib: ^2.4.1
  '@walletconnect/core@1.8.0':
    dependencies:
      tslib: ^2.4.1
  '@walletconnect/heartbeat@1.0.1':
    dependencies:
      events: ^3.3.0
  '@walletconnect/iso-crypto@1.8.0':
    dependencies:
      '@walletconnect/encoding': ^1.0.2
      tslib: ^2.4.1
  '@walletconnect/jsonrpc-provider@1.0.6':
    dependencies:
      events: ^3.3.0
  '@walletconnect/jsonrpc-ws-connection@1.0.5':
    dependencies:
      events: ^3.3.0
  '@walletconnect/socket-transport@1.8.0':
    dependencies:
      tslib: ^2.4.1
  '@walletconnect/utils@1.8.0':
    dependencies:
      tslib: ^2.4.1
  '@yfi/sdk@1.2.0':
    dependencies:
      events: ^3.3.0
  app-builder-lib@^24.0.0-alpha.5:
    dependencies:
      dmg-builder: ^24.0.0-alpha.5
  asn1@0.2.6:
    dependencies:
      assert: ^2.0.0
  assert-plus@1.0.0:
    dependencies:
      assert: ^2.0.0
      util: ^0.12.5
  aws-sign2@0.7.0:
    dependencies:
      url: ^0.11.0
  aws4@1.11.0:
    dependencies:
      querystring: ^0.2.1
      url: ^0.11.0
      util: ^0.12.5
  bnb-javascript-sdk-nobroadcast@2.16.15:
    dependencies:
      '@babel/runtime': ^7.20.6
      buffer: ^6.0.2
  browserify-zlib@0.2.0:
    dependencies:
      assert: ^2.0.0
      buffer: ^6.0.2
      util: ^0.12.5
  chakra-ui-steps@1.8.0:
    dependencies:
      '@chakra-ui/icon': ^3.0.12
      '@chakra-ui/styled-system': ^2.3.5
      '@chakra-ui/system': ^2.2.3
      '@chakra-ui/theme-tools': ^2.0.13
      '@chakra-ui/transition': ^2.0.12
      '@chakra-ui/utils': ^2.0.12
  cipher-base@1.0.4:
    dependencies:
      string_decoder: ^1.3.0
  combined-stream@1.0.8:
    dependencies:
      util: ^0.12.5
  core-util-is@1.0.3:
    dependencies:
      buffer: ^6.0.2
  delayed-stream@1.0.0:
    dependencies:
      util: ^0.12.5
  electron-builder-notarize@1.5.0:
    dependencies:
      builder-util: ^24.0.0-alpha.3
  electron-is-dev@2.0.0:
    dependencies:
      electron: 16.0.7
  electron-updater@5.3.0:
    dependencies:
      electron: 16.0.7
  ensure-error@2.1.0:
    dependencies:
      util: ^0.12.5
  eslint-config-react-app@7.0.1:
    dependencies:
      '@babel/plugin-syntax-flow': ^7.18.6
      '@babel/plugin-transform-react-jsx': ^7.19.0
  eth-block-tracker@4.4.3:
    dependencies:
      '@babel/core': ^7.20.5
  eth-url-parser@1.0.4:
    dependencies:
      util: ^0.12.5
  ethereumjs-util@7.1.5:
    dependencies:
      assert: ^2.0.0
      buffer: ^6.0.2
  extsprintf@1.3.0:
    dependencies:
      assert: ^2.0.0
      util: ^0.12.5
  extsprintf@1.4.1:
    dependencies:
      assert: ^2.0.0
      util: ^0.12.5
  http-signature@1.2.0:
    dependencies:
      util: ^0.12.5
  https-browserify@1.0.0:
    dependencies:
      url: ^0.11.0
  jsprim@1.4.2:
    dependencies:
      util: ^0.12.5
  ndjson@1.5.0:
    dependencies:
      os: npm:os-browserify@^0.3.0
  pngjs@3.4.0:
    dependencies:
      assert: ^2.0.0
      buffer: ^6.0.2
      util: ^0.12.5
  psl@1.9.0:
    dependencies:
      punycode: ^2.1.1
  react-native-codegen@0.70.6:
    dependencies:
      '@babel/core': ^7.20.5
      '@babel/preset-env': ^7.20.2
  react-router-breadcrumbs-hoc@4.1.0:
    dependencies:
      '@babel/runtime': ^7.20.6
  readable-stream@2.3.7:
    dependencies:
      events: ^3.3.0
  readable-stream@3.6.0:
    dependencies:
      buffer: ^6.0.2
      events: ^3.3.0
  request-promise@4.2.6:
    dependencies:
      os: npm:os-browserify@^0.3.0
  request@2.88.2:
    dependencies:
      fs: npm:noist@1.0.0
      querystring: ^0.2.1
      url: ^0.11.0
      util: ^0.12.5
  ripemd160@2.0.2:
    dependencies:
      buffer: ^6.0.2
  safe-buffer@5.1.2:
    dependencies:
      buffer: ^6.0.2
  safe-buffer@5.2.1:
    dependencies:
      buffer: ^6.0.2
  safer-buffer@2.1.2:
    dependencies:
      buffer: ^6.0.2
  split2@2.2.0:
    dependencies:
      string_decoder: ^1.3.0
  sshpk@1.17.0:
    dependencies:
      util: ^0.12.5
  stream-browserify@3.0.0:
    dependencies:
      events: ^3.3.0
  stream-http@3.2.0:
    dependencies:
      url: ^0.11.0
  through2@2.0.5:
    dependencies:
      util: ^0.12.5
  tough-cookie@3.0.1:
    dependencies:
      url: ^0.11.0
      util: ^0.12.5
  verror@1.10.0:
    dependencies:
      util: ^0.12.5
  web3-eth-abi@1.8.1:
    dependencies:
      buffer: ^6.0.2
  web3-providers-ws@1.7.4:
    dependencies:
      url: ^0.11.0
  xhr2-cookies@1.1.0:
    dependencies:
      os: npm:os-browserify@^0.3.0
      url: ^0.11.0
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
pnpFallbackMode: none
supportedArchitectures:
  os:
    - darwin
    - linux
    - win32
yarnPath: .yarn/releases/yarn-3.3.0.cjs
